### PR TITLE
Fixes #131 using Debug format to display errors

### LINKED ISSUE #131: `Simple` display should show `Debug` representations of input / expectations.
The `Display` impl for `Simple` shows raw output and expectations, which is awkward for whitespace, such as '\n':

Example:

```
use chumsky::primitive::{end, just};
use chumsky::Parser;

type Error = chumsky::error::Simple<char>;

fn main() {
    match parser().then_ignore(end()).parse("\nblah") {
        Ok(_) => panic!("Should not happen."),
        Err(es) => {
            for e in es {
                println!("{}", e);
            }
        }
    }
}

fn parser() -> impl Parser<char, (), Error = Error> {
    just("foo")
        .ignored()
        .or(just("\r\n").repeated().ignored())
        .or(just(' ').repeated().at_least(1).ignored())
}
```

-gives output:

```
found '
 was expectedend of input, f, 
```

Note also that sending raw whitespace (either inputs or expectations) behaves differently on different platforms and terminal types.

A `Debug`-style representation would be more useful for users, something like:

```
found '\n', was expecting 'f', '\r', or '\n'
```

### PR DESCRIPTION
**Pull request by dark-fusion**
This change introduces a Debug-style representation for `Simple`. It
should close issue #131 as the output now closely matches the desired
output discussed in the issue.

There may be some edge-cases or areas for improvement. In that case,
please let me know and I'll be happy to revise the PR.

### CODE REVIEW

File: src/error.rs [hunk 1]
```diff
@@ -309,11 +309,11 @@ impl<I: fmt::Display + Hash + Eq, S: Span> fmt::Display for Simple<I, S> {
...
         // TODO: Take `self.reason` into account
 
-        if let Some(found) = &self.found {
-            write!(f, "found '{}'", found)?;
+        let found = if let Some(found) = &self.found {
+            format!("{}", found)
         } else {
-            write!(f, "found end of input")?;
-        }
+            format!("found end of input")
```
Comment (bew) [inline src/error.rs:315]:
```suggestion
            format!("end of input")
```
otherwise you'd get `found found end of input ...`

File: src/error.rs [hunk 2]
```diff
@@ -325,18 +325,21 @@ impl<I: fmt::Display + Hash + Eq, S: Span> fmt::Display for Simple<I, S> {
...
-            )?,
+            _ => {
+                write!(
+                    f,
+                    r"found {:?}, but one of {:?} was expected",
+                    found,
+                    self.expected
+                        .iter()
+                        .map(|expected| match expected {
+                            Some(x) => format!("{}", x),
```
Comment (bew) [inline src/error.rs:336]: don't you need `{:?}` here ?

File: src/error.rs (hunk 1 above)
Comment (dark-fusion) [reply src/error.rs:315]: Definitely true. I agree with this change. I overlooked that part.

File: src/error.rs (hunk 2 above)
Comment (dark-fusion) [reply src/error.rs:336]: This is the tricky bit. I played around with it for a bit and you can use `{:?}` here, but you'll get very strange output. The escape `\` tokens are included in the format string.

There seems to be several different ways one could do this. I want to introduce a solution that doesn't involve messing with trait bounds or anything else. I'm sure there is a more elegant and/or more optimized way to handle this.

Comment (bew) [reply src/error.rs:336]: I mean, did you try to put `{:?}` here and remove leave a simple `{}` line 331 for the `.. one of {} was expected`

otherwise I guess it'll use the debug output of the debug output, leading to many `\`

File: src/error.rs [hunk 3]
```diff
@@ -325,18 +325,21 @@ impl<I: fmt::Display + Hash + Eq, S: Span> fmt::Display for Simple<I, S> {
...
+            _ => {
+                write!(
+                    f,
+                    "found {:?}, but one of {:?} was expected",
+                    found,
+                    self.expected
+                        .iter()
+                        .map(|expected| match expected {
+                            Some(x) => format!("{}", x),
+                            None => found.to_string(),
```
Comment (bew) [inline src/error.rs:337]: I'm wondering, why use `found` here?

File: src/error.rs [hunk 4]
```diff
@@ -325,18 +325,21 @@ impl<I: fmt::Display + Hash + Eq, S: Span> fmt::Display for Simple<I, S> {
                     None => format!("end of input"),
```
Comment (bew) [inline src/error.rs:325]: and I think you missed a change in the few lines above this line (but I can't put a comment there)

File: src/error.rs (hunk 2 above)
Comment (dark-fusion) [reply src/error.rs:336]: I'll take a closer, more careful look and implement things as per your suggestions. I may have missed something crucial because my intuition is telling me that your approach is correct.

File: src/error.rs (hunk 3 above)
Comment (dark-fusion) [reply src/error.rs:337]: I'm not very familiar with the codebase and I suppose I tried to make as small a change as possible. I don't like this, either. I don't have a good explanation for this.

With that said, I will clean this section up. Thank you for pointing this out.

File: src/error.rs (hunk 4 above)
Comment (dark-fusion) [reply src/error.rs:325]: Got it.

I really appreciate your time and your help. Thank you for reviewing this with me. I will make the changes that you suggest.

**Comment by zesterer** [comment]
Seems like @bew has reviewed this already! Many thanks to you both. Ping me when you feel it's ready!

**Comment by dark-fusion** [comment]
@zesterer The PR should be good to go. I made the suggested changes and pushed them. Please feel free to let me know if anything doesn't look right.

Thanks!

**Comment by zesterer** [comment]
Thanks for the PR! I might make an attempt to reduce instances of allocation later, but for now I'm happy to accept it.

**Comment by nathan-at-least** [comment]
Thanks for these two fixes, which address the main `chumsky` problems I have in my current project. When will this PR be included in a new release?

**Comment by zesterer** [comment]
@nathan-at-least I need to find the time/energy to prepare a new release. Perhaps this week some time. For now, you can point your `Cargo.toml` to the git repository.
